version: '3.1'

services:

  db:
    container_name: mysql
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    #ports:
    #  - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql

  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8081:80'
    volumes:
      - ./src:/var/www/laravel_docker:rw
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
volumes:
  db-volume: